name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main



jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - name: Install goimports
      run: go get golang.org/x/tools/cmd/goimports
    - name: Check code
      uses: actions/checkout@v3
    - run: goimports -d -local "github.com/jessicagreben/adventofcode" $(find . -name "*.go") 
    
#     - uses: actions/checkout@v3
#     - name: Set up Go
#       uses: actions/setup-go@v3
#       with:
#         go-version: 1.19
#       env:
#         GOPATH: $HOME

#     - name: Install goimports
#       run: |
#         GOBIN=$PWD/bin go install golang.org/x/tools/cmd/goimports@v0.4.0
#         ./bin/goimports -d -local "github.com/jessicagreben/adventofcode" $(find . -name "*.go") 
    - name: run gofmt
      run: gofmt -d $(find . -name "*.go") 
#     - name: run go vet
#       run: go vet ./...
    - name: run staticcheck
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        install-go: false
    - name: Unit Tests
      run: go test ./...
