name: Test Auto Merge

on:
  pull_request:
    branches: [ main ]
    paths: '2019/**/test.go'

jobs:
  approve-and-merge:
    runs-on: ubuntu-latest
    if:  startsWith(github.head_ref, 'autopr/')
    name: Approve and Merge
    steps:
    - name: Approve Pull Request
      run: gh pr review ${{ github.head_ref }} --approve
    - name: Merge Pull Request
      run: gh pr merge ${{ github.head_ref }} --merge --auto --delete-branch
