name: Test Auto Merge

on:
  pull_request:
    branches: [ main ]
    paths: '2019/**/test.go'

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  run_if:
    if:  startsWith(github.head_ref, 'autopr/')
  approve-and-merge:
    name: Approve and Merge
    runs-on: ubuntu-latest
    steps:
    - name: Approve Pull Request
      run: gh pr review ${{ github.head_ref }} --approve
    - name: Merge Pull Request
      run: gh pr merge ${{ github.head_ref }} --merge --auto --delete-branch
